### ISSUE TITLE
output path of validated jars

### ISSUE THREAD

**Issue by robstoll** [gradle/wrapper-validation-action#25]
Would be nice if the check would outptut the path of the verified gradle-wrapper.jar
This way I could count it to do a simple verification if it caught all of them and not that a bug in the validation wrapper makes me believe everything is fine when it's not.

**Comment by Marcono1234** [comment]
This already exists, doesn't it? For example here is the action log for https://github.com/junit-team/junit5-samples/actions/runs/6143544499/job/16667204762, which shows the paths after the checksums:
> ```
> ✓ Found known Gradle Wrapper JAR files:
>  0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15 junit5-jupiter-extensions/gradle/wrapper/gradle-wrapper.jar
>  0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15 junit5-jupiter-starter-gradle-groovy/gradle/wrapper/gradle-wrapper.jar
>  0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15 junit5-jupiter-starter-gradle-kotlin/gradle/wrapper/gradle-wrapper.jar
>  0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15 junit5-jupiter-starter-gradle/gradle/wrapper/gradle-wrapper.jar
>  0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15 junit5-migration-gradle/gradle/wrapper/gradle-wrapper.jar
>  0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15 junit5-multiple-engines/gradle/wrapper/gradle-wrapper.jar
> ```

Or do you mean it should store the paths as output of the action so that subsequent workflow steps can access them?

> This way I could count it

There is the `min-wrapper-count` action input; maybe that would be useful for your use case?

**Comment by robstoll** [comment]
looks like this was improved in the meantime 🙂 thanks for the hint regarding min-wrapper-count

**Comment by robstoll** [comment]
@Marcono1234 can you point me to the documentation regarding `min-wrapper-count`?

**Comment by robstoll** [comment]
closing this issue as IMO nothing is left todo
